# Generated by Django 5.1.7 on 2025-03-13 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=500)),
                ('link_github', models.URLField()),
                ('tecnology', models.CharField(choices=[('DJANGO', 'django'), ('PYTHON', 'python'), ('DART', 'dart'), ('FLUTTER', 'flutter'), ('CSS', 'css'), ('POSTGRESQL', 'PostgreSQL')], default=None, max_length=20)),
            ],
        ),
    ]
