# Generated by Django 5.1.7 on 2025-03-13 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_project_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='image',
        ),
        migrations.AlterField(
            model_name='project',
            name='tecnology',
            field=models.CharField(choices=[('DJANGO', 'django.svg'), ('PYTHON', 'python.svg'), ('DART', 'dart.svg'), ('FLUTTER', 'flutter.svg')], max_length=20),
        ),
    ]
