# Generated by Django 5.1.7 on 2025-03-13 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_project_image_alter_project_tecnology'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='image/<django.db.models.fields.CharField>'),
        ),
        migrations.AlterField(
            model_name='project',
            name='tecnology',
            field=models.CharField(choices=[('DJANGO', 'django.svg'), ('PYTHON', 'python.svg'), ('DART', 'dart.svg'), ('FLUTTER', 'flutter.svg')], default=None, max_length=20),
        ),
    ]
