# Generated by Django 5.1.7 on 2025-03-13 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_project_image_alter_project_tecnology'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='image',
        ),
    ]
