# Generated by Django 5.1.7 on 2025-03-13 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='tecnology',
            field=models.CharField(choices=[('DJANGO', 'django.svg'), ('PYTHON', 'python.svg'), ('DART', 'dart.svg'), ('FLUTTER', 'flutter.svg')], default=None, max_length=20, null=True),
        ),
    ]
