# Generated by Django 5.1.7 on 2025-03-13 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_project_tecnology_advice'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/<django.db.models.fields.CharField>'),
        ),
    ]
