# Generated by Django 5.1.7 on 2025-03-14 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_project_tecnology'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='tecnology',
            field=models.CharField(blank=True, choices=[('images/django.svg', 'DJANGO'), ('images/python.svg', 'PYTHON'), ('images/dart.svg', 'DART'), ('images/flutter.svg', 'FLUTTER')], default='django.svg', max_length=20),
        ),
    ]
